version: '3.9'

services:
  postgres:
    image: ankane/pgvector:v0.5.1
    ports:
      - 5432:5432
    volumes:
      - postgres_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=chatbot
  
  unstructured-api:
    image: downloads.unstructured.io/unstructured-io/unstructured-api:0.0.56
    ports:
      - 8001:8000

  langchain-service:
    image: langchain-server:0.0.5
    depends_on: 
      - postgres
      - unstructured-api
    profiles:
      - do-not-start
    ports:
      - 8000:8000
    command: uvicorn app.main:app --host 0.0.0.0
    environment:
      - OPENAI_API_KEY=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
      - SERPAPI_API_KEY=9a51cd3b4d5ce0b4a341656caac3fa6b86046e3e83e7eaa35330da96fb3d174a
      - UNSTRUCTURED_API_URL=http://unstructured-api:8000/general/v0/general
      - SQLALCHEMY_DATABASE_URL=postgresql://postgres:123456@postgres:5432/chatbot
  
  # neo4j:
  #   image: neo4j:4.4.27-community
  #   ports:
  #     - 7474:7474
  #     - 7687:7687
  #   environment:
  #     - NEO4J_AUTH=neo4j/pleaseletmein
  #     - NEO4J_PLUGINS=["apoc"]
  #   volumes:
  #     - neo4j_db:/data

volumes:
  neo4j_db:
    driver: local

  postgres_db:
    driver: local