version: '3.9'

services:
  postgres:
    image: ankane/pgvector:v0.5.1
    ports:
      - 5432:5432
    volumes:
      - postgres_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=chatbot
  
  unstructured-api:
    image: downloads.unstructured.io/unstructured-io/unstructured-api:0.0.56
    profiles:
      - do-not-start
    ports:
      - 8001:8000

  mongodb:
    image: amd64/mongo:5
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456

  langchain-backend:
    image: langchain-backend:0.0.1
    depends_on: 
      - postgres
      - unstructured-api
      - mongodb
    ports:
      - 8080:8080
    profiles:
      - do-not-start
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080
    environment:
      - UNSTRUCTURED_API_URL=http://unstructured-api:8000/general/v0/general
      - SQLALCHEMY_DATABASE_URL=postgresql://postgres:123456@postgres:5432/chatbot
      - MONGO_DATABASE_URL=mongodb://root:123456@mongodb/chatbot?authSource=admin&retryWrites=true&w=majority

  langchain-frontend:
    image: langchain-frontend:0.0.1
    depends_on:
      - langchain-backend
    ports:
      - 3000:3000
    profiles:
      - do-not-start
    environment:
      - LANGCHAIN_SERVER_URL=http://langchain-backend:8080
  
  # neo4j:
  #   image: neo4j:4.4.27-community
  #   ports:
  #     - 7474:7474
  #     - 7687:7687
  #   environment:
  #     - NEO4J_AUTH=neo4j/pleaseletmein
  #     - NEO4J_PLUGINS=["apoc"]
  #   volumes:
  #     - neo4j_db:/data

volumes:
  neo4j_db:
    driver: local

  postgres_db:
    driver: local